,python,x,08.01.2018 22:23,file:///home/python/.config/libreoffice/4;